name: Pipeline Workflow

on:
  push:
    branches: [ "dev-fiap-001" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      database_create:
        description: 'Trigger database creation pipeline'
        required: false 

jobs:
  call_ci_pipeline:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: CI-Pipeline - Continuous Integration
        uses: tshadz-fiap-postech-soat3/ci-pipeline/.github/workflows/ci-pipeline.yml@main

  call_database_creation_pipeline:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' && github.event.inputs.database_create == 'true'
    steps:
      - name: Trigger Database Creation Pipeline
        uses: tshadz-fiap-postech-soat3/terraform-database/.github/workflows/terraform-plan-pipeline-ci.yml@main
