name: Pipeline Workflow

on:
  push:
    branches: [ "dev-fiap-001" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  call-workflow-branch-ref:
    uses: tshadz-fiap-postech-soat3/ci-pipeline/.github/workflows/ci-pipeline.yml@dev-fiap-001
    secrets: inherit
